-- MySQL Script generated by MySQL Workbench
-- Wed Nov  4 15:28:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema confort-gym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema confort-gym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `confort-gym` DEFAULT CHARACTER SET utf8 ;
USE `confort-gym` ;

-- -----------------------------------------------------
-- Table `confort-gym`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(160) NOT NULL,
  `last_session` DATETIME NULL,
  `token` VARCHAR(255) NOT NULL,
  `token_password` VARCHAR(255) NOT NULL,
  `password_token` VARCHAR(255) NULL,
  `password_request` INT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `activo` INT NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rol_idx` (`id_rol` ASC) ,
  CONSTRAINT `fk_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `confort-gym`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`niveles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`niveles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_nivel` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(165) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`ejercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`ejercicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `repeticiones` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `animacion` VARCHAR(45) NOT NULL,
  `id_tipo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_idx` (`id_tipo` ASC) ,
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `confort-gym`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(160) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `edad` INT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `cod_ingreso` VARCHAR(255) NULL,
  `cod_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk-user_idx` (`cod_usuario` ASC) ,
  CONSTRAINT `fk-user`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `confort-gym`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`rutinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`rutinas` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre_rutina` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `tipo_rutina` INT NOT NULL,
  `id_nivel` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_nivel_idx` (`id_nivel` ASC) ,
  CONSTRAINT `fk_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `confort-gym`.`niveles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`rutinas_de_ejercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`rutinas_de_ejercicios` (
  `id_rutina` INT NOT NULL,
  `id_ejercicio` INT NOT NULL,
  INDEX `fk_ejercicio_idx` (`id_ejercicio` ASC) ,
  INDEX `fk_rutina_idx` (`id_rutina` ASC) ,
  CONSTRAINT `fk_ejercicio`
    FOREIGN KEY (`id_ejercicio`)
    REFERENCES `confort-gym`.`ejercicios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rutina`
    FOREIGN KEY (`id_rutina`)
    REFERENCES `confort-gym`.`rutinas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`productos` (
  `codigo` INT NOT NULL  AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `stock` VARCHAR(45) ,
  `cantidad` VARCHAR(45) ,
  `imagen` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`productos_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`productos_pedidos` (
  `id_producto` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  INDEX `fk_cliente_idx` (`id_cliente` ASC) ,
  INDEX `fk_producto_idx` (`id_producto` ASC) ,
  CONSTRAINT `fk_clie`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `confort-gym`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produc`
    FOREIGN KEY (`id_producto`)
    REFERENCES `confort-gym`.`productos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`sesion_entrenamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`sesion_entrenamiento` (
  `id_sesion` INT NOT NULL AUTO_INCREMENT,
  `asistencia` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `hora_ingreso` VARCHAR(45) NULL,
  `activo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sesion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`sesiones_programadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`sesiones_programadas` (
  `codigo_sesion` INT NOT NULL,
  `codigo_cliente` INT NOT NULL,
  INDEX `fk_sesion_idx` (`codigo_sesion` ASC) ,
  INDEX `fk_cli_idx` (`codigo_cliente` ASC) ,
  CONSTRAINT `fksesi`
    FOREIGN KEY (`codigo_sesion`)
    REFERENCES `confort-gym`.`sesion_entrenamiento` (`id_sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkclie`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `confort-gym`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`rutinas_programadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`rutinas_programadas` (
  `id_rutina` INT NOT NULL,
  `cod_sesion` INT NOT NULL,
  INDEX `fk_ru_idx` (`id_rutina` ASC) ,
  INDEX `fk_sesion_idx` (`cod_sesion` ASC) ,
  CONSTRAINT `fk_rut`
    FOREIGN KEY (`id_rutina`)
    REFERENCES `confort-gym`.`rutinas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesi`
    FOREIGN KEY (`cod_sesion`)
    REFERENCES `confort-gym`.`sesion_entrenamiento` (`id_sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`rutinas_creadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`rutinas_creadas` (
  `id` INT NOT NULL,
  `id_rutina` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `activa` TINYINT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cr_idx` (`id_rutina` ASC) ,
  INDEX `fk_cli_idx` (`id_cliente` ASC) ,
  CONSTRAINT `fk_cr`
    FOREIGN KEY (`id_rutina`)
    REFERENCES `confort-gym`.`rutinas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cli`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `confort-gym`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `mensaje` VARCHAR(255) NOT NULL,
  `leido` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idNotificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort-gym`.`notificar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`notificar` (
  `cod` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_usuario2` INT NOT NULL,
  `cod_notificacion` INT NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_u1_idx` (`id_usuario` ASC) ,
  INDEX `fk_n_idx` (`cod_notificacion` ASC) ,
  CONSTRAINT `fk_u1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `confort-gym`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_n`
    FOREIGN KEY (`cod_notificacion`)
    REFERENCES `confort-gym`.`notificacion` (`idNotificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `confort-gym` ;

-- -----------------------------------------------------
-- Placeholder table for view `confort-gym`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort-gym`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `confort-gym`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `confort-gym`.`view1`;
USE `confort-gym`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
